name: HelloWorld

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello all to the AZ-400 CLass by Himanshu!!!"

      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: List Repo
        run: ls -la


  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
      - name: 🔨 Simulate Build
        run: |
          echo "Building the application..."
          echo "Build completed at $(date)" > build-report.txt
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v5
        with:
          name: build-report
          path: build-report.txt
          retention-days: 2

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 🧪 Simulate Tests
        run: echo "✅ All tests passed!"
      - name: download artifact
        uses: actions/download-artifact@v5
        with:
          name: build-report
      - name: Inspect Artifact
        run: cat build-report.txt
      

          
