name: HelloWorld

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello all to the AZ-400 CLass by Himanshu!!!"

      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: List Repo
        run: ls -la

      - name: Generate ASCII Art
        run: |
          sudo apt-get install -y figlet
          figlet "AZ-400"
          echo "----------------------------"
          figlet -f digital "GitHub Actions"
          echo "✅ ASCII art generated!"
