name: HelloWorld

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello all to the AZ-400 CLass by Himanshu!!!"

      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: List Repo
        run: ls -la
